### PR TITLE
Fitting and plotting improvements

### PR DESCRIPTION
**Pull request by reneeotten**
This PR introduces some enhancements for fitting / plotting, in addition to some other small changes:
1. allow for different fitting methods (both command-line argument and in methods)
2. change to a non-interactive backend so that using the software remotely (e.g., a cluster) also works.

I would be happy to work a bit more on the plotting (and perhaps fitting) part, but before doing so I'd like your opinion.
* output for CEST/CPMG data; right now we write .pdf/.fit/.exp files in the Plots directory for CEST, but only .pdf and .fit files for CPMG - is this on purpose? If not, it would be good to decide on what to do and do it consistently for all experiments.

* there is some code duplication in <cest, cpmg>/plotting.py, to be more precise the functions "sigma_estimator", "set_lim" and "group_data". Would it make sense to move these to experiments/plotting.py instead? Also, right now you don't use the simga_estimator in the CPMG plots, is that on purpose?

### CODE REVIEW

**Comment by chriswaudby** [comment]
Couple of thoughts:
* Making it easier to run on a cluster is useful and pretty timely for me - I've been hacking it with scripts to do a grid search over the weekend. A useful next step for me would be a mechanism to override and freeze parameters at the command line to avoid layers of scripting. 
* is it good practise to allow setting a key parameter like the fitting algorithm in two places? Which has priority? Perhaps this could be merged into a more general command line override like I suggest above?

**Comment by reneeotten** [comment]
I am not sure whether it's good practice to allow setting the fitmethod in two places... I, however, think that it is convenient and not too bad in this case. If you just want to use the default method (i.e., don't use a method file) but still want to change the fitting method you can use the command line argument. On the other hand, if you specify different steps in a method file then it would be nice to be able to also change the fitting method. Regarding fixing/varying paramaters from the command-line, that seems much more like a headache to do in a general way.... 

My main reason for allowing the use of different fitting methods is that, ideally, you'll either do a grid search and then use leastsquares or have another more global minimization algorithm. I have looked a bit into differential evolution, and that was one of the reasons to implement changing the fitmethod in the methods file (i.e., you do a leastsq minimization first, then fix everything except for kex and pop and do differential evolution).

I follow the `lmfit` approach that if nothing is specified (on the command-line that is), it will use `leastsq`. The next step is checking for `fitmethod` in the method file. If it's not there then it will fallback on the command-line option. In my mind that was the most general way of doing it, but I am open to other suggestions.

I agree with you that an easy way to perform a grid search is one of the most needed features for chemex. There have been [discussions](https://github.com/lmfit/lmfit-py/issues/283) on the lmfit page on this topic before. I think we should try to implement this with them instead of re-inventing the wheel or doing all kind of scripting around it (as you did now and I did in the past as well). I will go and take a closer look at that code, hopefully in the not-too-far-future :)

**Comment by gbouvignies** [comment]
Hi Renee,

Those are all great changes. Just a few remarks: 

  1) Some of the fitting methods throw an error message when picked. These are all the methods for which a Jacobian need be provided. 
  2) `least_squares`, which should behave very similarly to `leastsq` with standard options, leads to crazy parameter values as soon as a parameter is bounded. I am not sure what is the issue here, but this could be a problem with how `lmfit` uses this method, something to check. This is a shame because this method has great potential, especially for robust fits. 
  3) `differential_evolution` throws an error message when either`min` or `max` values of a parameter are not set to a finite value.

For (1) and (2), I suggest we remove these methods from the list of available methods. Regarding (3), we should check whether finite bounds are set when this method is picked. If not, we should probably enforce some parameter specific default bound values.

I agree .pdf/.fit/.exp files should be written for all type of experiments. "sigma_estimator", "set_lim" and "group_data" can certainly go to "experiments/plotting.py". 

I don't use "sigma_estimator" for CPMG plots because the error bars on R2 values (1) are not symmetrical and (2) directly depend on R2 values. Therefore it is not as relevant for CPMG profiles as it is for intensity profiles, where error bars are symmetrical and identical for all the intensities in the profile.

**Comment by reneeotten** [comment]
I agree with you on most points, just leave this PR open and I will make the changes. Regarding your comments:
1. Yes, I will remove all methods that want more information than we are willing to give :)
2. That is indeed weird, I will try and take a look if there is something obvious...
3. Differential evolution indeed requires indeed finite bounds right now. However, if have implemented `scipy.optimize.brute` in `lmfit` and the discussion on that PR was also about how to handle infinite bounds - we could probably do the same for `differential_evolution.`. But, I guess that we probably prefer a predictable grid-search over a random one (and therefore will use `brute`) or not? 

I will take a look at the fitting part; if you want to change the output/plotting stuff that sounds good. You should be able to commit to this branch, so we can just keep everything synchronized here and merge it when everything is done!

**Comment by gbouvignies** [comment]
Thanks Renee! Looks good to me. Any reason not to merge?

Is the 'brute' fitting method working? Would you have any example showing how to use it?

**Comment by reneeotten** [comment]
@gbouvignies it still needs some more work, so I think waiting a little bit longer would be good. 

I would like to finish the visualization of the `brute` grid search first. It doesn't doesn't work right now as the plotting function needs the `MinimizerResult` and right now only the fitted `params` are returned. I need to re-factor the fitting code a little bit to get this to work. I can certainly provide an example as well on how to use it.

After that you can certainly merge it so that we can continue so that we can try and avoid to many merge conflicts as we continue working on the code.

In addition, related to earlier comments in this PR: 
1. the writing of the output file should be a bit more consistent (i.e., write .pdf/.fit/.exp files also for CPMG experiments) - I'll try and see if I can do that still within this PR as well. 
2. as you also noticed, the `least_squares` gives unexpected results - I think this is due to the implementation in `lmfit` and I have opened an Issue on their GitHub page.

So unless you're really in a hurry to merge it, I would like to get a few more days to wrap this up properly (I'll try to finish it before or in the weekend). 

Thanks!

**Comment by reneeotten** [comment]
@gbouvignies I think this should be good to go now!

It keeps now the `MinimizerResult` around as much as possible instead of returning the best-fit-parameters. As you'll see it needed a bit of fiddling around to combine everything again in one `MinimizerResult` in case of `independent_clusters`.

I compared the results for all provided examples between the "original" feature_to_profile branch and this PR and they are -as far as I can tell- identical. There are some small differences in the reported statistics, but I think there were a few issues with the previous version. In case you run into trouble with the `brute` method and/or other `lmfit` related error messages, please install the latest `master` from the GitHub - a new version that will work for sure will be released soon-ish.

I would suggest to make sure first that all the functionality is present and working as intended and then we can work on some code refactoring (there are probably some places were we can clean up unused stuff a bit). 

What about opening issues for things that need to be done so that we can keep track of stuff?

**Comment by gbouvignies** [comment]
@reneeotten Great! Merging this one.

(As you mentioned, I had to install the latest `master` of `lmfit` from the GitHub to have it work.)

**Pull request merged**
