### PR TITLE
Code reformatting

### PR DESCRIPTION
**Pull request by reneeotten**
A PR as discussed in #22:
* I added configuration settings for "yapf" and "isort" to setup.cfg
* told yapf which parts of the code to ignore
* consistent code style and order of import statements can be achieved by running:
`isort` and `yapf -r -i -e=*version*` in the chemex/chemex directory

In addition, I added a few more docstrings here and there.

### CODE REVIEW

**Comment by gbouvignies** [comment]
Great ! I am happy with all your changes, except the maximum of 79 characters per line that comes with the PEP 8 style. It sometimes just makes things look ugly. I'd rather to set a hard limit to 120 characters (compatible with Github website) and put a soft limit in my editor to 79, so that I can do my best not to go beyond.

This can be done by adding to the `[yapf]` section of `setup.cfg`:
    column_limit = 120

**Comment by reneeotten** [comment]
I agree that sometimes it does not make sense to have a hard limit at 79 characters. The approach to set it to 120 is however not great either, because that will reformat all lines assuming that your intended length is 120 characters. In other words, if you decided to break a line manually before 80 characters because it "makes sense or looks good", yapf will undo these changes if total line length is < 120. 

There are ways to set penalties for certain things, for example "split_penalty_excess_character" but I haven't really figured how to tweak those to get the behavior you'd prefer. I'll fiddle around with it a bit more to see if I can get something that is acceptable in most cases (it will never be ideal for everything). Another option would be to set the "split_penalty_excess_character" to zero and let yapf not split lines at all, but only do the other type of formatting, but that would kind of defeat the purpose...

**Comment by gbouvignies** [comment]
I actually find that 120 characters per line look pretty good – but this is my personal taste of course. There is much debate about this part of PEP 8, to the point that PEP 8 now includes the statement that "it is okay to increase the nominal line length from 80 to 100 characters". I'll be ok with 100 but 120 works well too. However I would not go below 100, in part because I fear that it would potentially force us to pick shorter variable names, which can be detrimental to readability.

**Comment by reneeotten** [comment]
okay, you are the boss! I have updated the PR to re-format the code with 120 character line length. I did run all examples and everything works - at least, it gives the same output/results as before, so I didn't break anything :)

**Comment by gbouvignies** [comment]
Thanks Renee! I have been playing a bit with yapf this evening and found that 100 character line length looks reasonable. Maybe this could be a good compromise. What do you think? Anyway, if you like it like that, I'm happy to merge as is. Otherwise, please don't hesitate to change `column_width` to 100.

I recently heard about git hooks, which if I understand correctly could automatically run `isort` and `yapf` on each commit. Could be handy. Do you know anything about it?

**Comment by reneeotten** [comment]
I didn't see the statement about increasing the length to 100 characters... let's do that, I changed the PR accordingly.

In addition, I did run "docformatter", which formats the docstrings according to PEP 257. We are probably not going to change the docstring as much as the code itself, but it doesn't hurt to run this once in a while. 

If you're happy with it, please feel free to merge - thanks!

**Pull request merged**
