### PR TITLE
Refactor the codebase

### PR DESCRIPTION
**Pull request by gbouvignies**
This massive refactoring of the code aims at:
  - adding type hints to the code;
  - replacing 'jsonschema' with 'pydantic' to validate setting files;
  - using 'rich' to add colors and nicer formatting to the terminal
    output;
  - making use of some SOLID principles to make the code more robust
    and easier to change (use of factories, updating the plugin
    architecture to help adding new features in the future, ...).

Many additional changes were made along the way to improve code
readability and reduce code complexity.

Convention to the import statements now follows the "from ... import
function/class" format. Not necessarily considered best practice, but it
shortens type annotations.

### CODE REVIEW

**Comment by reneeotten** [comment]
@gbouvignies I did a quick read through of the changes (which are quite extensive!) and it looks all very good and clean code. It would be nice though to "stabilize" the code a bit - although I am sure that's your intention with this PR, unless you just really enjoy doing major overhauls of the codebase ;) 

What's your plan here, do you consider this a "stable" version that is about ready-for-a-release? If so, you could probably merge the and I'd be happy to do a bit more testing and looking at the code (I plan to do some fitting anyway in the near future)...

**Comment by gbouvignies** [comment]
@reneeotten You're absolutely right on both points: I aim at stabilizing the code with this PR and – yes ;) – I also really enjoy doing major overhauls of the codebase. That being said, stabilizing things is now the priority and the actual purpose of this PR.

I'm currently drafting a website to accompany this version, which should serve as documentation and provide links to the different examples available on GitHub. I'll create a PR with a rough draft of it in the coming days. Feedbacks and/or contributions from you and others will be more than welcome and will undoubtedly improve things by a lot.

**Comment by reneeotten** [comment]
great @gbouvignies - let me know if you want me to take a look at anything! Do you have plans to merge this PR soon-ish or is there additional work needed (and, if so, do you need any help in testing or anything)?

**Comment by gbouvignies** [comment]
@reneeotten I wanted to have a documentation more or less ready to merge it, but it takes longer than expected. I'll merge it and later tag it for release as soon as there's a documentation ready.

**Comment by viochemist** [comment]
I'd be happy to help with the documentation if you like, as long as it's not substantially different from what I'm used to. Just let me know

**Pull request merged**
